# Generated by Django 3.2.25 on 2025-08-29 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Developer', 'Developer'), ('Viewer', 'Viewer')], default='Developer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('team_invitation', 'Team Invitation'), ('invitation_accepted', 'Invitation Accepted'), ('invitation_declined', 'Invitation Declined'), ('team_member_added', 'Team Member Added'), ('team_role_changed', 'Team Role Changed'), ('pr_created', 'Pull Request Created'), ('pr_merged', 'Pull Request Merged'), ('build_failed', 'Build Failed'), ('build_passed', 'Build Passed')], default='general', max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at'], name='core_notifi_user_id_bd2d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='core_notifi_type_2da3a2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='core_notifi_created_d0c445_idx'),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='invited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.team'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['token'], name='core_teamin_token_af5421_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['email', 'status'], name='core_teamin_email_426c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['expires_at'], name='core_teamin_expires_411792_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teaminvitation',
            unique_together={('team', 'email', 'status')},
        ),
    ]
